language: go
go:
  - 1.5
before_install:
  - go get -t ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - sh ci/test.sh
